[package]
name = "cl-format"
version = "0.1.0"
authors = ["ccQpein"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
syn = { version = "1", features = ["full", "extra-traits"] }
quote = "1"

cl-format-macros = { path = "../cl-format-macros" }
